#!/usr/bin/env node
const PROCESS = require('process');
const READLINE = require('readline');
const { Client } = require('pg');

function logAndExit(err) {
  console.log(err);
  process.exit(1);
}

class ExpenseData {
  constructor() {
    this.client = new Client({ database: 'expenses' });
  }

  async setupSchema() {
    let tableCreationQuery = `CREATE TABLE expenses (
      id serial PRIMARY KEY,
      amount numeric(6,2) NOT NULL,
      memo text NOT NULL,
      created_on date NOT NULL
    )`;

    let res = await this.client.query(`
      SELECT COUNT(*)
      FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'expenses'
    `).catch(err => logAndExit(err));

    if (res.rows[0].count === '0') {
      await this.client.query(tableCreationQuery).catch(err => logAndExit(err));
    }
  }

  displayExpenses(res) {
    res.rows.forEach(tuple => {
      let columns = [
        `${tuple.id}`.padStart(3),
        tuple.created_on.toDateString().padStart(10),
        tuple.amount.padStart(12),
        tuple.memo
      ];
      console.log(columns.join(' | '));
    });
  }

  async listExpenses() {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));
    let res = await this.client.query("SELECT * FROM expenses ORDER BY created_on")
      .catch(err => logAndExit(err));

    this.displayCount(res.rowCount);
    this.displayExpenses(res);
    if (res.rowCount > 1) {
      this.displayTotal(res.rows);
    }

    await this.client.end().catch(err => logAndExit(err));
  }

  async addExpense(amount, memo) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let date = new Date();
    date = date.toLocaleDateString();
    let queryText = 'INSERT INTO expenses (amount, memo, created_on) VALUES ($1, $2, $3)';
    let queryValues = [amount, memo, date];

    await this.client.query(queryText, queryValues).catch(err => logAndExit(err));

    await this.client.end().catch(err => logAndExit(err));
  }

  async searchExpenses(term) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let queryText = 'SELECT * FROM expenses WHERE memo ILIKE $1';
    let res = await this.client.query(queryText, [`%${term}%`]).catch(err => logAndExit(err));

    this.displayCount(res.rowCount);
    this.displayExpenses(res);
    if (res.rowCount > 1) {
      this.displayTotal(res.rows);
    }
    await this.client.end().catch(err => logAndExit(err));
  }

  async deleteExpense(id) {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    let res = await this.client.query("SELECT * FROM expenses WHERE id = $1", [id]).catch(err => logAndExit(err));
    if (res.rowCount === 1) {
      await this.client.query("DELETE FROM expenses WHERE id = $1", [id]).catch(err => logAndExit(err));
      console.log("The following expense has been deleted:");
      this.displayExpenses(res);
    } else {
      console.log(`There is no expense with the id '${id}'.`);
    }

    await this.client.end().catch(err => logAndExit(err));
  }

  async deleteAllExpenses() {
    await this.client.connect().catch(err => logAndExit(err));
    await this.setupSchema().catch(err => logAndExit(err));

    await this.client.query("DELETE FROM expenses").catch(err => logAndExit(err));
    console.log('All expenses have been deleted.');
    await this.client.end().catch(err => logAndExit(err));
  }

  displayCount(rowCount) {
    if (rowCount === 0) {
      console.log("There are no expenses.");
    } else {
      let verb = rowCount > 1 ? "are" : "is";
      let noun = rowCount > 1 ? "expenses" : "expense";
      console.log(`There ${verb} ${rowCount} ${noun}.`);
    }
  }

  displayTotal(rows) {
    let total = rows.reduce((acc, row) => acc + Number(row.amount), 0);
    console.log('-'.repeat(50));
    console.log(`Total: ${String(total).padStart(30)}`);
  }
}

class CLI {
  constructor() {
    this.application = new ExpenseData();
  }
  static HELP() {
    return `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field`;
  }

  displayHelp() {
    console.log(CLI.HELP());
  }

  run(args) {
    if (args.length === 2) {
      this.displayHelp();
    } else if (args[2] === 'list') {
      this.application.listExpenses();
    } else if (args[2] === 'add') {
      if (args.length < 5) {
        console.log('You must provide an amount and memo.');
      } else {
        let amount = args[3];
        let memo = args[4]
        this.application.addExpense(amount, memo);
      }
    } else if (args[2] === 'search') {
      let term = args[3];
      this.application.searchExpenses(term);
    } else if (args[2] === 'delete') {
      let id = args[3];
      this.application.deleteExpense(id);
    } else if (args[2] === 'clear') {
      let rl = READLINE.createInterface({
        input: process.stdin,
        output: process.stdout
      });
      let questionText = 'This will remove all expenses. Are you sure? (enter y to confirm)';
      rl.question(questionText, (answer) => {
        if (answer === 'y') {
          this.application.deleteAllExpenses();
        }
        rl.close();
      });
    }
  }
}

let cli = new CLI();
cli.run(PROCESS.argv);

